name: Update Static Cached Leaderboards

permissions:
  contents: write

on:
  repository_dispatch:
    types: [refresh_leaderboards]
  workflow_dispatch:

jobs:
  update-leaderboards:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make Sure API is Reachable
        run: |
          for i in {1..3}; do
            if [ $(curl -s -o /dev/null -w "%{http_code}" "https://api.johnfoxweb.com") -eq 200 ]; then
              exit 0
            else
              sleep 40
            fi
          done
          exit 1
      
      - name: Create cache directory
        run: mkdir -p static/cachedLeaderboards
      
      - name: Fetch trueskill data
        run: curl -s "https://api.johnfoxweb.com/api/leaderboard/trueskill" > "static/cachedLeaderboards/trueskill.json"

      - name: Fetch players outlasted data
        run: curl -s "https://api.johnfoxweb.com/api/leaderboard/players-outlasted" > "static/cachedLeaderboards/players-outlasted.json"

      - name: Fetch ROI data
        run: curl -s "https://api.johnfoxweb.com/api/leaderboard/roi" > "static/cachedLeaderboards/roi.json"

      - name: Fetch first place data
        run: curl -s "https://api.johnfoxweb.com/api/leaderboard/firstplace" > "static/cachedLeaderboards/firstplace.json"

      - name: Fetch ITM percent data
        run: curl -s "https://api.johnfoxweb.com/api/leaderboard/itmpercent" > "static/cachedLeaderboards/itmpercent.json"

      - name: Fetch community disconnectedness data
        run: curl -s "https://api.johnfoxweb.com/api/leaderboard/community-disconnectedness" > "static/cachedLeaderboards/community-disconnectedness.json"
      
      - name: Commit and Push
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add static/cachedLeaderboards/*.json
          git commit -m "Update all leaderboard data" || exit 0
          git push